- hosts: 192.168.43.188
  tasks:
  - name: create yum repository for docker
    yum_repository:
      name: docker
      description: this is docker repo
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no

  - command: "yum install docker-ce --nobest --allowerasing -y"

  - name: Start Docker service
    service:
      name: "docker"
      state: started

  - name: Install python3
    package:
      name: "python3"
      state: present

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Pull docker image
    docker_image:
      name: "httpd"
      source: pull

  - name: Making a directory on managed node
    file:
      path: "/root/docker_ws"
      state: directory

  - name: Copying webpage to managed node directory
    copy:
      src: "home.html"
      dest: "/root/docker_ws"

  - name: Create a data container
    docker_container:
      name: "my_os"
      image: "httpd"
      volumes:
              - "/root/docker_ws:/usr/local/apache2/htdocs/"
      ports:
              - "8080:80"
      state: started

  - name: do not permit traffic in default zone on port 8080/tcp
    firewalld:
      port: 8080/tcp
      permanent: yes
      state: disabled


